version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  etl_pipeline:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
